import {
  AlertIcon,
  AppsoutageIcon,
  ArrowIcon,
  BadgeIcon,
  BellIcon,
  BidLandscapeIcon,
  BoltIcon,
  BoundingboxIcon,
  CalendarMonthIcon,
  CancelIcon,
  ChevronIcon,
  ClockIcon,
  CodeIcon,
  CodesimpleIcon,
  CopyIcon,
  DataarrayIcon,
  DatainfoalertIcon,
  DatabaseIcon,
  DatabaseSearchIcon,
  DatasetIcon,
  DinamicscreenIcon,
  ErrorIcon,
  ErrorIconIcon,
  EyeIcon,
  FilterIcon,
  GitbranchIcon,
  GridIcon,
  GithubIcon,
  GoogleIcon,
  HealingIcon,
  HouseIcon,
  InfoIconIcon,
  InspectIcon,
  KeyIcon,
  LightbulbIcon,
  ListIcon,
  ListallIcon,
  LockIcon,
  MailIcon,
  MedalIcon,
  MenuIcon,
  MessageSquareTextIcon,
  MoneyIcon,
  MoonIcon,
  PlusIcon,
  ProblemIcon,
  ReviewIcon,
  RoseIcon,
  RoseCustomIcon,
  RoseRulesIcon,
  Schedule1Icon,
  SchoolIcon,
  SdkIcon,
  SearchIcon,
  SettingsIcon,
  ShieldIcon,
  ShareIcon,
  StacksIcon,
  StarIcon,
  StarFilledIcon,
  SuccessIconIcon,
  SunIcon,
  SupportIcon,
  TableIcon,
  TagIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TrashIcon,
  TvOptionsInputSettingsIcon,
  UnionIcon,
  UpdateIcon,
  UserIcon,
  ViewInArIcon,
  VitalSignsIcon,
  WandStarsIcon,
  WarningIconIcon,
} from './svg-icons';

export const svgIconComponents = {
  alert: AlertIcon,
  'apps-outage': AppsoutageIcon,
  arrow: ArrowIcon,
  badge: BadgeIcon,
  bell: BellIcon,
  'bid-landscape': BidLandscapeIcon,
  bolt: BoltIcon,
  'bounding-box': BoundingboxIcon,
  'calendar-month': CalendarMonthIcon,
  cancel: CancelIcon,
  chevron: ChevronIcon,
  clock: ClockIcon,
  code: CodeIcon,
  codesimple: CodesimpleIcon,
  copy: CopyIcon,
  'data-array': DataarrayIcon,
  'data-info-alert': DatainfoalertIcon,
  database: DatabaseIcon,
  'database-search': DatabaseSearchIcon,
  dataset: DatasetIcon,
  'dinamic-screen': DinamicscreenIcon,
  error: ErrorIcon,
  'error-icon': ErrorIconIcon,
  eye: EyeIcon,
  filter: FilterIcon,
  gitbranch: GitbranchIcon,
  grid: GridIcon,
  github: GithubIcon,
  google: GoogleIcon,
  healing: HealingIcon,
  house: HouseIcon,
  'info-icon': InfoIconIcon,
  inspect: InspectIcon,
  key: KeyIcon,
  lightbulb: LightbulbIcon,
  list: ListIcon,
  'list-all': ListallIcon,
  lock: LockIcon,
  mail: MailIcon,
  medal: MedalIcon,
  menu: MenuIcon,
  'message-square-text': MessageSquareTextIcon,
  money: MoneyIcon,
  moon: MoonIcon,
  plus: PlusIcon,
  problem: ProblemIcon,
  review: ReviewIcon,
  rose: RoseIcon,
  'rose-custom': RoseCustomIcon,
  'rose-rules': RoseRulesIcon,
  'schedule-1': Schedule1Icon,
  school: SchoolIcon,
  sdk: SdkIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  shield: ShieldIcon,
  share: ShareIcon,
  stacks: StacksIcon,
  star: StarIcon,
  'star-filled': StarFilledIcon,
  'success-icon': SuccessIconIcon,
  sun: SunIcon,
  support: SupportIcon,
  table: TableIcon,
  tag: TagIcon,
  'thumbs-down': ThumbsDownIcon,
  'thumbs-up': ThumbsUpIcon,
  trash: TrashIcon,
  'tv-options-input-settings': TvOptionsInputSettingsIcon,
  union: UnionIcon,
  update: UpdateIcon,
  user: UserIcon,
  'view-in-ar': ViewInArIcon,
  'vital-signs': VitalSignsIcon,
  'wand-stars': WandStarsIcon,
  'warning-icon': WarningIconIcon,
} as const;

export type IconName = keyof typeof svgIconComponents;
